config/routes.rb
Rails.application.routes.draw do
  get 'invoices/index'
  get 'invoices/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :invoices, only: %i[new create index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  has_many :invoice_items, dependent: :destroy
  accepts_nested_attributes_for :invoice_items, reject_if: proc { |attributes| attributes["name"].blank? || attributes["description"].blank? || attributes["price"].blank? || attributes["qty"].blank? }

  STATUSES = ["draft", "sent", "paid"]

  STATUS_CLASS = {
      :draft => "badge badge-secondary",
      :sent => "badge badge-primary",
      :paid => "badge badge-success"
  }

  def subtotal
    self.invoice_items.map { |item| item.qty * item.price }.sum
  end

  def discount_calculated
    subtotal * (self.discount / 100.0)
  end

  def vat_calculated
    (subtotal - discount_calculated) * (self.vat / 100.0)
  end

  def total
    subtotal - discount_calculated + vat_calculated
  end

  def status_class
    STATUS_CLASS[self.status.to_sym]
  end
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :full_name, :company, :phone_number, :street_address, :city, :state, :postal_code, :country ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [ :full_name, :company, :phone_number, :street_address, :city, :state, :postal_code, :country ])
  end

  def after_sign_up_path_for(_resource)
    "/invoices"
  end

  def after_sign_in_path_for(_resource)
    "/invoices"
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@invoice.id}",
               page_size: 'A4',
               template: "invoices/show.html.erb",
               layout: "pdf.html",
               orientation: "Portrait",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end
  end

  def new
    @invoice = Invoice.new
    @invoice.invoice_items.build
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to invoices_path
    else
      render :new
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:to_full_name, :to_street_address, :to_city, :to_state, :to_postal_code, :to_country, :to_phone_number, :status, :discount, :vat)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/index.html.erb
<div class="container">
  <h1>Invoices</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">From</th>
        <th scope="col">To</th>
        <th scope="col">Status</th>
        <th scope="col">Discount (%)</th>
        <th scope="col">VAT (%)</th>
        <th scope="col">TOTAL</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% if !@invoices.empty? %>
        <% @invoices.each do |invoice| %>
          <tr>
            <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
            <td><%= current_user.full_name %></td>
            <td><%= invoice.to_full_name %></td>
            <td><span class="<%= invoice.status_class %>"><%= invoice.status %></span></td>
            <td><%= invoice.discount %></td>
            <td><%= invoice.vat %></td>
            <td><%= number_to_currency(invoice.total) %></td>
            <td><%= link_to 'View', invoice_path(invoice), id: "view-link" %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>No invoices</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/new.html.erb
<div class="container mt-3">
  <h2>Create a new invoice</h2>

  <%= simple_form_for(@invoice) do |f| %>
    <%= f.input :to_full_name, required: true %>
    <%= f.input :to_address, required: true %>
    <%= f.input :to_phone, required: true %>
    <%= f.input :status, collection: Invoice::STATUSES, required: true %>
    <%= f.input :discount, required: true %>
    <%= f.input :vat, required: true %>
    <%= f.simple_fields_for :invoice_items do |invoice_items_form| %>
      <%= invoice_items_form.input :name, required: true %>
      <%= invoice_items_form.input :description, required: true %>
      <%= invoice_items_form.input :price, required: true %>
      <%= invoice_items_form.input :qty, required: true %>
    <% end %>
    <div class="form-actions">
      <%= f.button :submit, "Create", class: "login" %>
    </div>
  <% end %>
</div>

app/views/invoices/show.html.erb
<div class="container">
  <div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
      <tr class="top">
        <td colspan="4">
          <table>
            <tr>
              <td class="title">
                <%= image_tag wicked_pdf_asset_base64('company_logo.png') %>
              </td>

              <td>
                Invoice #: <b><%= @invoice.id %></b>
                <br>
                Created: <b><%= @invoice.created_at.strftime('%d/%m/%Y') %></b>
                <br>
                Due: <b><%= (@invoice.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                <br>
                Status: <span class="<%= @invoice.status_class %>"><%= @invoice.status %></span>
              </td>
            </tr>
          </table>
        </td>
      </tr>

      <tr class="information">
        <td colspan="4">
          <table>
            <tr>
              <td>
                <b><%= current_user.full_name %></b><br>
                <%= current_user.street_address %>, <%= current_user.city %>, <%= current_user.state %>, <%= current_user.postal_code %>, <%= current_user.country %> <br>
                <i class="far fa-envelope"></i> <%= current_user.email %><br>
                <i class="fas fa-phone"></i> <%= current_user.phone_number %>
              </td>

              <td>
                <b><%= @invoice.to_full_name %></b><br>
                <%= @invoice.to_address %><br>
                <i class="far fa-envelope"></i> <%= @invoice.to_email %><br>
                <i class="fas fa-phone"></i> <%= @invoice.to_phone %>
              </td>
            </tr>
          </table>
        </td>
      </tr>

      <tr class="heading">
        <td>Payment Method</td>
        <td colspan="2"></td>
        <td class="right">Cache</td>
      </tr>

      <tr class="details">
        <td>Delivery Method</td>
        <td colspan="2"></td>
        <td class="right">1000</td>
      </tr>

      <tr class="heading">
        <td>Item</td>
        <td class="right">Price</td>
        <td class="right">Qty</td>
        <td>Total</td>
      </tr>

      <% @invoice.invoice_items.each do |invoice_item| %>
        <tr class="item">
            <td>
                <%= invoice_item.name %><br>
                <small><%= invoice_item.description %></small>
            </td>

            <td class="right">
                <%= number_to_currency(invoice_item.price) %>
            </td>

            <td class="right">
                x <%= invoice_item.qty %>
            </td>

            <td>
                <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
            </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="4"></td>
      </tr>

      <tr>
        <td colspan="2"></td>
        <td><b>Subtotal</b></td>
        <td><%= number_to_currency(@invoice.subtotal) %></td>
      </tr>

      <tr>
        <td colspan="2"></td>
        <td><b>Discount (<%= @invoice.discount %>%)</b></td>
        <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
      </tr>

      <tr>
        <td colspan="2"></td>
        <td><b>VAT (<%= @invoice.vat %>%)</b></td>
        <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
      </tr>

      <tr class="heading">
        <td colspan="2"></td>
        <td><b>TOTAL:</b></td>
        <td>
            <b><%= number_to_currency(@invoice.total) %></b>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <%= link_to 'Invoices', invoices_path, class: "btn btn-outline-secondary mx-2" %>
          <% if action_name.to_sym == :show %>
            <%= link_to 'DOWNLOAD PDF', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>